apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qpny7xrfs-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qpny7xrfs-go 
  name: qpny7xrfs-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qpny7xrfs-go 
